baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: blue
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true

languages:
  en:
    languageName: English
    title: Yaska1706
    subtitle: Your site subtitle
    keywords: 'Code & Coffee'
    copyright: Yaska1706
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    author:
      name : Yaska1706
      email: yasinkinyua@gmail.com

    params:
      logo:
        logoText: Yaska1706
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: showcase
        name: Showcase
        url: /showcase